[package]
name = "worker"
version = "0.1.1"
edition = "2021"

authors = ["Tighlit Badis <badis.tighlit@gmail.com>"]

[dependencies]
messages = { path = "../messages"}
serde = "1.0.125"
serde_json = "1.0.66"
serde_derive = "1.0.125"
