[package]
name = "worker"
version = "0.1.0"
edition = "2021"


authors = ["Tighlit Badis <badis.tighlit@gmail.com>"]


[dependencies]
messages = { path = "../messages"}
serde = { version= "1.0.196", features=["derive"] }
serde_json = "1.0.66"

