[package]
name = "worker"
version = "0.1.0"
edition = "2021"


authors = ["Tighlit Badis <badis.tighlit@gmail.com>"]


[dependencies]
message = { path = "../message"}
serde = { version= "1", features=["derive"] }
serde_json = "1"

